project:
  type: website

website:
  title: "Pedro H. A. Anjos"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: research.qmd
        text: Research

      - href: publications.qmd
        text: Publications

      - href: teaching.qmd
        text: Teaching

      - href: cv.qmd
        text: CV

      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false




